apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/consul_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-default-consul-consul-server-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi